# Makefile
# Řešení IOS-DU2, 28.4.2024
# Autor: Hugo Bohácsek (xbohach00), FIT
CFLAGS=-std=gnu99 -Wall -Wextra -Werror -pedantic -pthread

all: proj2

proj2: proj2.c
	gcc $(CFLAGS) proj2.c -o proj2

clean:
	$(RM) proj2 proj2.out
# ./proj2 8 4 10 4 5