/**
 * @file dialogaddvariable.h
 * @author Eliška Křeménková (xkremee00)
 * @brief Declaration of the DialogAddVariable class that handles adding new variable to the model
 * @date 2025-05-09
 */

#ifndef DIALOGADDVARIABLE_H
#define DIALOGADDVARIABLE_H

#include <QDialog>

namespace Ui {
class DialogAddVariable;
}

/**
 * @class DialogAddVariable
 * @brief A dialog window for creating and configuring a new variable.
 *
 * This class provides a simple UI for entering the name, type, and initial value
 * of a variable. It is used as a modal dialog and returns user input
 * through getter methods after acceptance.
 */
class DialogAddVariable : public QDialog
{
    Q_OBJECT

public:
    /**
     * @brief Construct a new DialogAddVariable object
     * 
     * @param parent Parent widget, default is nullptr
     */
    explicit DialogAddVariable(QWidget *parent = 0);

    /**
     * @brief Destroy the DialogAddVariable object
     */
    ~DialogAddVariable();

    /**
     * @brief Get the Var Name object
     * 
     * @return QString name of the variable received from the dialog
     */
    QString getVarName() const;

    /**
     * @brief Get the Var Type object
     * 
     * @return QString type of the variable received from the dialog (available types: string, int, float)
     */
    QString getVarType() const;

    /**
     * @brief Get the Var Value object
     * 
     * @return QString value of the variable received from the dialog
     */
    QString getVarValue() const;

private:
    /**
     * @brief Pointer to the UI elements defined in the dialogaddvariable.ui file.
     * 
     * This is automatically generated by Qt's user interface compiler (uic) and provides
     * access to all widgets and layout elements created in the Qt Designer for DialogAddVariable.
     */
    Ui::DialogAddVariable *ui;
};

#endif // DIALOGADDVARIABLE_H
