/**
 * @file dialogaddstate.h
 * @author Eliška Křeménková (xkremee00)
 * @brief Declaration of the DialogAddState class that handles adding new state to the model
 * @date 2025-05-09
 */

#ifndef DIALOGADDSTATE_H
#define DIALOGADDSTATE_H

#include <QDialog>

namespace Ui {
class DialogAddState;
}

/**
 * @class DialogAddState
 * @brief A dialog window for creating and configuring a new state.
 *
 * This class provides a simple UI for entering
 * - state name
 * - state purpose - Initial or Final
 * - state position
 * 
 * It is used as a modal dialog and returns user input
 * through getter methods after acceptance.
 */
class DialogAddState : public QDialog
{
    Q_OBJECT

public:
    /**
     * @brief Construct a new Dialog Add State object
     * @param parent Parent widget, default is nullptr
     */
    explicit DialogAddState(QWidget *parent = 0);

    /**
     * @brief Destroy the Dialog Add State object
     */
    ~DialogAddState();

    /**
     * @brief Get the state name from the dialog
     * @return name
     */
    QString getStateName() const;

    /**
     * @brief Check if the state was set as initial in the dialog
     * @return true if set as Initial
     */
    bool isStartState() const;

    /**
     * @brief Check if the state was set as final in the dialog
     * @return true if set as Final
     */
    bool isFinalState() const;

    /**
     * @brief Get the state x position from the dialog
     * @return x position
     */
    int getPosX() const;

    /**
     * @brief Get the state y position from the dialog
     * @return y position
     */
    int getPosY() const;

private:
    /**
     * @brief Pointer to the UI elements defined in the dialogaddstate.ui file.
     * 
     * This is automatically generated by Qt's user interface compiler (uic) and provides
     * access to all widgets and layout elements created in the Qt Designer for DialogAddState.
     */
    Ui::DialogAddState *ui;
};

#endif // DIALOGADDSTATE_H
