/**
 * @file mainwindow.h
 * @author Eliška Křeménková (xkremee00)
 * @brief main window of the application
 * @date 2025-05-09
 */
#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include "automatoneditor.h"
#include <QMainWindow>
#include <QLineEdit>
#include <QPushButton>

namespace Ui {
class MainWindow;
}

/**
 * @class MainWindow
 * @brief The MainWindow class represents the initial UI window of the application.
 * 
 * It provides the user with options to create a new automaton or open an existing one
 * from a file. This class serves as the entry point to the application and handles user interaction in the startup screen.
 */
class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    /**
     * @brief Construct a new Main Window object
     * @param parent Parent QWidget, used for memory management
     */
    explicit MainWindow(QWidget *parent = 0);

    /**
     * @brief Destroy the Main Window object
     */
    ~MainWindow();

private slots:

    /**
     * @brief Slot for handling "Create New" button click
     * 
     * This will open the automaton editor window with clean graphic scene
     */
    void on_pushButton_create_new_clicked();

    /**
     * @brief Slot for handling "Open from" button click
     * 
     * This will open the automaton editor window with loaded automaton from the given file
     */
    void on_pushButton_open_from_clicked();

private:
    /**
     * @brief Pointer to the UI elements defined in the mainwindow.ui file.
     * 
     * This is automatically generated by Qt's user interface compiler (uic) and provides
     * access to all widgets and layout elements created in the Qt Designer for MainWindow.
     */
    Ui::MainWindow *ui;
};

#endif // MAINWINDOW_H
